<?php
function h($s) {
    return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8');
}

function csrf_field() {
    if (session_status() === PHP_SESSION_NONE) session_start();
    if (empty($_SESSION['csrf'])) $_SESSION['csrf'] = bin2hex(random_bytes(32));
    return '<input type="hidden" name="csrf" value="' . $_SESSION['csrf'] . '">';
}

function csrf_check() {
    if (empty($_POST['csrf']) || $_POST['csrf'] !== ($_SESSION['csrf'] ?? '')) {
        http_response_code(403);
        die('CSRF validation failed. Sila refresh dan cuba semula.');
    }
}

function flash_set($key, $msg) {
    $_SESSION['flash'][$key] = $msg;
}

function flash_get($key) {
    $v = $_SESSION['flash'][$key] ?? null;
    unset($_SESSION['flash'][$key]);
    return $v;
}

function flash_html() {
    $ok  = flash_get('ok');
    $err = flash_get('err');
    $out = '';
    if ($ok)  $out .= '<div class="flash flash-ok">✓ ' . h($ok) . '</div>';
    if ($err) $out .= '<div class="flash flash-err">✗ ' . h($err) . '</div>';
    return $out;
}

function redirect($url) {
    header('Location: ' . $url);
    exit;
}

function is_superadmin() {
    global $adminUser;
    return !empty($adminUser) && $adminUser['role'] === 'superadmin';
}

function setting($pdo, $key, $default = '') {
    static $cache = null;
    if ($cache === null) {
        $rows  = $pdo->query('SELECT `key`, value FROM mn_settings')->fetchAll();
        $cache = array_column($rows, 'value', 'key');
    }
    return $cache[$key] ?? $default;
}

function regen_config($pdo) {
    $s = [];
    foreach ($pdo->query('SELECT `key`, value FROM mn_settings')->fetchAll() as $r) {
        $s[$r['key']] = $r['value'];
    }
    $wa  = addslashes($s['wa_num']     ?? '60123456789');
    $wad = addslashes($s['wa_display'] ?? '+60 12-345 6789');
    $em  = addslashes($s['site_email'] ?? 'info@mnsports.my');
    $nm  = addslashes($s['site_name']  ?? 'MN Sports');
    $ig  = addslashes($s['site_ig']    ?? '');
    $fb  = addslashes($s['site_fb']    ?? '');
    $tt  = addslashes($s['site_tt']    ?? '');

    $content = "<?php\n"
             . "/* Auto-generated by Admin Panel — jangan edit manual */\n"
             . "define('WA_NUM',     '$wa');\n"
             . "define('WA_URL',     'https://wa.me/' . WA_NUM);\n"
             . "define('WA_DISPLAY', '$wad');\n"
             . "define('SITE_EMAIL', '$em');\n"
             . "define('SITE_NAME',  '$nm');\n"
             . "define('SITE_IG',    '$ig');\n"
             . ($fb ? "define('SITE_FB',    '$fb');\n" : "// define('SITE_FB', '$fb');\n")
             . ($tt ? "define('SITE_TT',    '$tt');\n" : "// define('SITE_TT', '$tt');\n")
             . "\n";

    $path = __DIR__ . '/../../includes/config.php';
    return file_put_contents($path, $content) !== false;
}
